---
title: "Honour Board"
description: |
  A summary of key performances throughout our history
output: distill::distill_article
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(dplyr)
library(tidyr)
library(readr)
library(purrr)
library(stringr)
library(here)
library(reactable)
library(htmltools)
library(knitr)
library(rmarkdown)
```


```{r message=FALSE, warning=FALSE, include=FALSE}
honour_roll <- read_csv(here::here("data", "honour-board.csv"))
bowling <- read_csv(here::here("data", "bowling_combined.csv"))
batting <- read_csv(here::here("data", "batting_combined.csv"))

names(honour_roll) <- make.names(names(honour_roll))
```

```{r message=FALSE, warning=FALSE, include=FALSE}
seasons <- batting %>%
  select(season_id, season) %>% 
  distinct() %>%
  drop_na()

leading_runs <- batting %>% 
  filter(team == "The Nutty Cuckoo Super Kings") %>% 
  group_by(season_id, Batsmen) %>% 
  summarise(runs = sum(RunsScored)) %>%
  group_by(season_id) %>%
  slice_max(runs, n = 1) %>%
  mutate(top_runscorer = paste0(Batsmen, " (", runs, ")")) %>%
  select(season_id, top_runscorer) %>%
  left_join(seasons, by = "season_id") %>%
  group_by(season_id, season) %>%
  summarize(top_runscorer = str_c(top_runscorer, collapse = ", "))

leading_wickets <- bowling %>% 
  filter(team == "The Nutty Cuckoo Super Kings") %>% 
  group_by(season_id, Bowlers) %>% 
  summarise(wkts = sum(Wickets)) %>%
  group_by(season_id) %>%
  slice_max(wkts, n = 1) %>%
  mutate(most_wickets = paste0(Bowlers, " (", wkts, ")")) %>%
  select(season_id, most_wickets) %>%
  left_join(seasons, by = "season_id") %>%
 group_by(season_id, season) %>%
 summarize(most_wickets = str_c(most_wickets, collapse = ", "))

```


```{r echo=FALSE, message=FALSE, warning=FALSE}
df <- honour_roll %>%
  left_join(leading_runs, by = "season_id") %>%
  left_join(leading_wickets, by = c("season_id", "season")) %>%
  select(season_id, league_id, Season.Number, season, Position, Golden.Furphy, Golden.Bunny, top_runscorer, most_wickets, everything())
```


```{r}
reactable_function <- function(df, type = "batting"){
  reactable(df, 
          pagination = FALSE,
          #defaultSortOrder = "asc",
          #defaultSorted = "Season.Number",
          defaultColDef = colDef(
            sortNALast = TRUE,
            minWidth = 45,
            class = JS("function(rowInfo, colInfo, state) {
        // Highlight sorted columns
        for (var i = 0; i < state.sorted.length; i++) {
          if (state.sorted[i].id === colInfo.id) {
            return 'sorted'
          }
        }
      }"),
      headerClass = "box-score-header"),
      columns = list(      
        season_id = colDef(show = FALSE),
        league_id = colDef(show = FALSE),
        Season.Number = colDef(name = "#", width = 30),
        season = colDef(
          name = "Season",
          defaultSortOrder = "asc",
          cell = function(value, index) {
            season_id <- df[index, "season_id"]
            league_id <- df[index, "league_id"]
            season_url <- paste0(
              "https://www.lastmanstands.com/leagues/standings/t20&leagueid=",
              league_id,
              "&seasonid=",
              season_id,
              "&divisionid=0")
            tags$a(href = season_url, target = "_blank", value)
          }
        ),
        Position = colDef(width = 70),
        Golden.Furphy = colDef(name = "Golden Furphy"),
        Golden.Bunny = colDef(name = "Bunnoz Award"),
        top_runscorer = colDef(name = "Most Runs"),
        most_wickets = colDef(name = "Most Wkts"),
        Dream.Team = colDef(name = "League Team",
                            width = 120)
      ),
      showSortIcon = FALSE,
      highlight = TRUE,
      striped = TRUE,
      class = "box-score-tbl")
}
```
```{r}

div(class = "box-score",
    div(class = "box-score-title", "Honour Board"),
    reactable_function(df)
)


```


```{r ref.label="box_score", eval=FALSE}
```

```{r}
tags$link(href = "https://fonts.googleapis.com/css?family=Roboto:400,500&display=fallback", rel = "stylesheet")
```

```{css}
.box-score {
  font-family: 'Roboto', Helvetica, Arial, sans-serif;
}
.box-score a:hover {
  text-decoration: none;
}
.header {
  text-align: center;
  font-size: 20px;
}
.game-date {
  font-size: 16px;
}
.line-score {
  margin-top: 24px;
  text-align: center;
}
.line-score-tbl {
  margin: 0 auto;
  max-width: 500px;
  font-size: 15px;
}
.line-score-header {
  font-size: 13px;
  font-weight: 400;
}
.line-score-final {
  font-weight: 500;
}
.team-name {
  font-weight: 500;
}
.team-record {
  margin-left: 6px;
  color: hsl(0, 0%, 45%);
  font-size: 12px;
}
.box-score-title {
  margin-top: 24px;
  padding: 8px;
  background-color: hsl(205, 100%, 36%);
  color: hsl(0, 0%, 98%);
  font-size: 15px;
  font-weight: 400;
}
.box-score-tbl {
  font-size: 12px;
  letter-spacing: 0.2px;
}
.box-score-header {
  padding: 8px !important;
  border-bottom-width: 1px;
  background-color: hsl(205, 93%, 16%);
  color: hsl(0, 0%, 98%);
  font-weight: 400;
  font-size: 11px;
  text-transform: uppercase;
  transition: box-shadow 0.3s cubic-bezier(0.175, 0.885, 0.32, 1.275);
}
.box-score-header:hover,
.box-score-header[aria-sort="ascending"],
.box-score-header[aria-sort="descending"] {
  background-color: hsl(205, 100%, 36%);
}
.box-score-header[aria-sort="ascending"] {
  box-shadow: inset 0 10px 0 -6px #efaa10 !important;
}
.box-score-header[aria-sort="descending"] {
  box-shadow: inset 0 -10px 0 -6px #efaa10 !important;
}
.sorted {
  background-color: hsla(0, 0%, 60%, 0.1);
}
.box-score-total {
  font-size: 13px;
  font-weight: 500;
}
```

```{css echo=FALSE}
/* rmarkdown html documents */
.main-container {
  max-width: 1024px !important;
}
h1.title {
  display: none;
}
/* pkgdown articles */
.contents {
  width: inherit;
}
```

