---
title: "Latest Game"
description: |
  Stats from our most recent game
author:
  - name: James Day
date: "`r Sys.Date()`"
output: distill::distill_article
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
	echo = FALSE,
	message = FALSE,
	warning = FALSE
)
library(dplyr)
library(readr)
library(purrr)
library(stringr)
library(here)
library(reactable)
library(htmltools)
library(knitr)
library(rmarkdown)
source(here::here("scripts", "reactable_function.R"))

```

```{r load data, include=FALSE, echo = FALSE}
bowling <- read_csv(here::here("data", "bowling_detailed.csv"))
batting <- read_csv(here::here("data", "batting_detailed.csv"))
fielding <- read_csv(here::here("data", "fielding_detailed.csv"))
keeping <- read_csv(here::here("data", "keeping_detailed.csv"))
```



```{r bowling, layout="l-body-outset"}

bowling_df <- bowling %>% 
  filter(Team == "The Nutty Cuckoo Super Kings") %>%
  filter(StartDateTime == max(StartDateTime)) %>%
  mutate(Econ = RunsConceded/Over,
         dot.perc = BowlingDotBalls/(Over*5 + Ball),
         Name = paste0(FirstName, " ", LastName)) %>%
  rename(Wkts = Wickets,
         User.Id = Id, 
         Runs = RunsConceded,
         Dots = BowlingDotBalls,
         NB = NoBall) %>%
  select(User.Id, Name, Over, Ball, Runs, Wkts, Dots, NB, Wide, Econ, dot.perc) 



```

### Batting
```{r batting, layout="l-body-outset"}

batting_df <- batting %>%
  filter(Team == "The Nutty Cuckoo Super Kings") %>%
  filter(StartDateTime == max(StartDateTime)) %>%
  mutate(SR = RunsScored/BallsFaced*100,
         dot.perc = BattingDotBalls/BallsFaced,
         Name = paste0(FirstName, " ", LastName)) %>%
  rename(User.Id = Id,
         Dots = BattingDotBalls,
         Balls = BallsFaced,
         Runs = RunsScored) %>%
  arrange(Order) %>%
  select(User.Id, Name, Order, Runs, Balls, SR, Fours, Sixes, Dots, dot.perc) 


```

```{r}
fielding_df <- fielding  %>%
  filter(Team == "The Nutty Cuckoo Super Kings") %>%
  filter(StartDateTime == max(StartDateTime)) %>%
  mutate(Name = paste0(FirstName, " ", LastName)) %>%
  rename(User.Id = Id) %>%
  select(User.Id, Name, Catches, RunOuts) 

```

```{r}
keeping_df <- keeping  %>%
  filter(Team == "The Nutty Cuckoo Super Kings") %>%
  filter(StartDateTime == max(StartDateTime)) %>%
  mutate(Name = paste0(FirstName, " ", LastName)) %>%
  rename(User.Id = Id) %>%
  select(User.Id, Name, Catches, Stumpings, RunOuts, Byes) 

```




```{r, layout="l-body-outset"}


div(class = "box-score",
  div(class = "box-score-title", "Batting"),
  reactable_function(batting_df, NULL),
  div(class = "box-score-title", "Bowling"),
  reactable_function(bowling_df, NULL),
  div(class = "box-score-title", "Fielding"),
  reactable_function(fielding_df, NULL),
  div(class = "box-score-title", "Keeping"),
  reactable_function(keeping_df, NULL),
)

```

# Fines
Under construction, numbers probably wrong. Doesn't include manual fines yet. 

```{r fines}

batting_fines <- batting_df %>%
  mutate(`50` = ifelse(Runs >= 50, -4, NA),
         `SR<110` = ifelse(SR < 110 & Balls > 10, 6, NA),
         `SR<160` = ifelse(SR >= 110 & SR < 160 & Balls > 10, 3, NA),
         `<21` = ifelse(Runs < 21, 3, NA),
         Duck = ifelse(Runs == 0 & Balls > 1, 3, NA),
         Golden = ifelse(Runs == 0 & Balls == 1, 6, NA)) %>%
  group_by(Name) %>%
  mutate(Total = sum(`50`, `SR<110`, `SR<160`, `<21`, Duck, Golden, na.rm = TRUE)) %>%
  select(Order, User.Id, Name, Runs, SR, `50`:Total)

econ_fine <- function(overs, econ, field = NULL) {
  # change for field
  threshold <- 10
  
  if(floor(econ) < threshold) return(NA)
  
  round(econ - threshold) * 2 + overs * 2
  
}

bowling_fines <- bowling_df %>%
  group_by(Name) %>%
  mutate(econ_fine = econ_fine(Over, Econ),
         `3+` = ifelse(Wkts >= 3, -3, NA)) %>%
  mutate(total = econ_fine + `3+`) %>%
  select(User.Id, Name, Over, Runs, Wkts, Econ,econ_fine, `3+`, total)


batting_fines %>% kable()
bowling_fines %>% kable()
```




```{r ref.label="box_score", eval=FALSE}
```

```{r}
tags$link(href = "https://fonts.googleapis.com/css?family=Roboto:400,500&display=fallback", rel = "stylesheet")
```

```{css}
.box-score {
  font-family: 'Roboto', Helvetica, Arial, sans-serif;
}
.box-score a:hover {
  text-decoration: none;
}
.header {
  text-align: center;
  font-size: 20px;
}
.game-date {
  font-size: 16px;
}
.line-score {
  margin-top: 24px;
  text-align: center;
}
.line-score-tbl {
  margin: 0 auto;
  max-width: 500px;
  font-size: 15px;
}
.line-score-header {
  font-size: 13px;
  font-weight: 400;
}
.line-score-final {
  font-weight: 500;
}
.team-name {
  font-weight: 500;
}
.team-record {
  margin-left: 6px;
  color: hsl(0, 0%, 45%);
  font-size: 12px;
}
.box-score-title {
  margin-top: 24px;
  padding: 8px;
  background-color: hsl(205, 100%, 36%);
  color: hsl(0, 0%, 98%);
  font-size: 15px;
  font-weight: 400;
}
.box-score-tbl {
  font-size: 12px;
  letter-spacing: 0.2px;
}
.box-score-header {
  padding: 8px !important;
  border-bottom-width: 1px;
  background-color: hsl(205, 93%, 16%);
  color: hsl(0, 0%, 98%);
  font-weight: 400;
  font-size: 11px;
  text-transform: uppercase;
  transition: box-shadow 0.3s cubic-bezier(0.175, 0.885, 0.32, 1.275);
}
.box-score-header:hover,
.box-score-header[aria-sort="ascending"],
.box-score-header[aria-sort="descending"] {
  background-color: hsl(205, 100%, 36%);
}
.box-score-header[aria-sort="ascending"] {
  box-shadow: inset 0 10px 0 -6px #efaa10 !important;
}
.box-score-header[aria-sort="descending"] {
  box-shadow: inset 0 -10px 0 -6px #efaa10 !important;
}
.sorted {
  background-color: hsla(0, 0%, 60%, 0.1);
}
.box-score-total {
  font-size: 13px;
  font-weight: 500;
}
```

```{css echo=FALSE}
/* rmarkdown html documents */
.main-container {
  max-width: 1024px !important;
}
h1.title {
  display: none;
}
/* pkgdown articles */
.contents {
  width: inherit;
}
```
