---
title: "All time batting stats"
author:
  - name: James Day
date: "`r Sys.Date()`"
output: distill::distill_article
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(tidyverse)
library(here)
library(reactable)
library(htmltools)
source(here::here("scripts", "reactable_function.R"))
```

```{r load data, include=FALSE, echo = FALSE}

batting_df <- read_csv(here::here("data", "batting_summary.csv")) %>%
  filter(team == "The Nutty Cuckoo Super Kings") %>%
  select(-team)
```

```{r, layout="l-body-outset"}
div(class = "box-score",

  div(class = "box-score-title", "Batting"),
  reactable_function(batting_df, "batting"),

)
```


```{r ref.label="box_score", eval=FALSE}
```

```{r}
tags$link(href = "https://fonts.googleapis.com/css?family=Roboto:400,500&display=fallback", rel = "stylesheet")
```

```{css}
.box-score {
  font-family: 'Roboto', Helvetica, Arial, sans-serif;
}
.box-score a:hover {
  text-decoration: none;
}
.header {
  text-align: center;
  font-size: 20px;
}
.game-date {
  font-size: 16px;
}
.line-score {
  margin-top: 24px;
  text-align: center;
}
.line-score-tbl {
  margin: 0 auto;
  max-width: 500px;
  font-size: 15px;
}
.line-score-header {
  font-size: 13px;
  font-weight: 400;
}
.line-score-final {
  font-weight: 500;
}
.team-name {
  font-weight: 500;
}
.team-record {
  margin-left: 6px;
  color: hsl(0, 0%, 45%);
  font-size: 12px;
}
.box-score-title {
  margin-top: 24px;
  padding: 8px;
  background-color: hsl(205, 100%, 36%);
  color: hsl(0, 0%, 98%);
  font-size: 15px;
  font-weight: 400;
}
.box-score-tbl {
  font-size: 12px;
  letter-spacing: 0.2px;
}
.box-score-header {
  padding: 8px !important;
  border-bottom-width: 1px;
  background-color: hsl(205, 93%, 16%);
  color: hsl(0, 0%, 98%);
  font-weight: 400;
  font-size: 11px;
  text-transform: uppercase;
  transition: box-shadow 0.3s cubic-bezier(0.175, 0.885, 0.32, 1.275);
}
.box-score-header:hover,
.box-score-header[aria-sort="ascending"],
.box-score-header[aria-sort="descending"] {
  background-color: hsl(205, 100%, 36%);
}
.box-score-header[aria-sort="ascending"] {
  box-shadow: inset 0 10px 0 -6px #efaa10 !important;
}
.box-score-header[aria-sort="descending"] {
  box-shadow: inset 0 -10px 0 -6px #efaa10 !important;
}
.sorted {
  background-color: hsla(0, 0%, 60%, 0.1);
}
.box-score-total {
  font-size: 13px;
  font-weight: 500;
}
```

```{css echo=FALSE}
/* rmarkdown html documents */
.main-container {
  max-width: 1024px !important;
}
h1.title {
  display: none;
}
/* pkgdown articles */
.contents {
  width: inherit;
}
```